version: "3.8"

services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=Product_Service
      - JWT_SECRET=secret
    depends_on:
      - postgres

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/product-service
    depends_on:
      - mongo

  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Product_Service
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
