version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: basestructure
    ports:
      - "5432:5432"
    networks:
      - app-network

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=basestructure
      - JWT_SECRET=secret
    depends_on:
      - postgres
    networks:
      - app-network

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/product-service
    depends_on:
      - mongo
    networks:
      - app-network

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
